{
 "title": "Prusalink Exporter",
 "tags": [
  "home",
  "playlist_main"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "printer",
    "query": {
     "query": "label_values(prusalink_scrape_successful,printer)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Prusalink Printer $printer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "printer" },
  {
   "title": "🖨️ $printer",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_scrape_successful{printer=~\"$printer\"}",
     "legendFormat": "{{printer}}"
    }
   ]
  },
  {
   "title": "Job: Filename",
   "type": "stat",
   "gridPos": { "h": 3, "w": 10, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_job_info{printer=~\"$printer\"}",
     "legendFormat": "{{filename}}"
    }
   ]
  },
  {
   "title": "Job: Print Time Elapsed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_job_time_elapsed{printer=~\"$printer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job: Print Time Remaining",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_job_time_remaining{printer=~\"$printer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job: Estimated Completion",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(prusalink_job_time_remaining{printer=~\"$printer\"} + time())*1000",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "🌡️ $printer Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 18, "w": 19, "x": 5, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "prusalink_bed_temp_current{printer=~\"$printer\"}",
     "legendFormat": "Bed"
    },
    {
     "expr": "prusalink_bed_temp_desired{printer=~\"$printer\"}",
     "legendFormat": "Bed Target"
    },
    {
     "expr": "prusalink_nozzle_temp_current{printer=~\"$printer\"}",
     "legendFormat": "Nozzle"
    },
    {
     "expr": "prusalink_nozzle_temp_desired{printer=~\"$printer\"}",
     "legendFormat": "Nozzle Target"
    }
   ]
  },
  {
   "title": "Printer Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_printer_state{printer=~\"$printer\"} == 1",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Firmware Versions",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_server_firmware_version_info{printer=~\"$printer\"}",
     "legendFormat": "Server Version: {{version}}"
    },
    {
     "expr": "prusalink_server_firmware_version_info{printer=~\"$printer\"}",
     "legendFormat": "API Version: {{api}}"
    }
   ]
  },
  {
   "title": "Current Nozzle Diameter",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_nozzle_diameter{printer=~\"$printer\"}",
     "legendFormat": "Installed Nozzle"
    }
   ]
  },
  {
   "title": "Configured Flow Rate",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_flow_rate{printer=~\"$printer\"}",
     "legendFormat": "Flow Rate"
    }
   ]
  },
  {
   "title": "Configured Speed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_speed{printer=~\"$printer\"}",
     "legendFormat": "Speed"
    }
   ]
  },
  {
   "title": "Job: Print Progress",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 19, "x": 5, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_job_progress{printer=~\"$printer\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Z-Axis Height",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "mm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "prusalink_axis_z{printer=~\"$printer\"}",
     "legendFormat": "Z-height"
    }
   ]
  }
 ]
}